-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.hanif.smartstudy.data.model.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn okio.**
